from src.sk_common.sk_utilities.sk_ensure_path import h_ensure_path
from src.sk_common.sk_utilities.sk_get_project_icon import h_get_project_icon
from src.sk_common.sk_vars import APP_GLOBAL_COMMON_DATA_DPATH, APP_GLOBAL_DATA_DPATH, APP_GLOBAL_RESOURCES_DPATH, APP_IS_BUNDLED, APP_ROOT_DPATH, OS_WIN_APPDATA
APP_NAME = 'SKSRetriever'
APP_VERSION = '1.0.0'
APP_RESOURCES_DPATH = APP_GLOBAL_RESOURCES_DPATH if APP_IS_BUNDLED else APP_GLOBAL_RESOURCES_DPATH / APP_NAME
APP_DATA_WIN_DPATH = OS_WIN_APPDATA / APP_NAME
h_ensure_path(APP_DATA_WIN_DPATH)
APP_STEAM_SENTRY_DPATH = APP_DATA_WIN_DPATH / 'steam_login'
h_ensure_path(APP_STEAM_SENTRY_DPATH)
APP_STEAM_CACHE_DPATH = APP_DATA_WIN_DPATH / 'steam_cache'
h_ensure_path(APP_STEAM_CACHE_DPATH)
APP_STEAM_OUTPUT_DPATH = APP_DATA_WIN_DPATH / 'steam_output'
h_ensure_path(APP_STEAM_OUTPUT_DPATH)
APP_DATA_DPATH = APP_ROOT_DPATH / APP_NAME if APP_IS_BUNDLED else APP_GLOBAL_DATA_DPATH / APP_NAME
APP_LOGS_DPATH = APP_DATA_DPATH / 'logs'
APP_OUTPUT_DPATH = APP_DATA_DPATH
APP_CACHE_DPATH = APP_STEAM_CACHE_DPATH if APP_IS_BUNDLED else APP_GLOBAL_COMMON_DATA_DPATH / 'steam_cache'
APP_ICON_FPATH = h_get_project_icon(APP_RESOURCES_DPATH)
APP_LOG_FPATH = APP_LOGS_DPATH / f"{APP_NAME}.log"
APP_TOP_OWNERS_STEAMIDS = [
 76561198028121353,
 76561197993544755,
 76561198001237877,
 76561197979911851,
 76561198355625888,
 76561198237402290,
 76561198152618007,
 76561198213148949]
APP_REQUESTS_TIMEOUT = 60
APP_REQUESTS_HEADERS = {'User-Agent': 'Valve/Steam HTTP Client 1.0'}