from src.sk_common.sk_utilities.sk_get_project_icon import h_get_project_icon
from src.sk_common.sk_vars import APP_GLOBAL_COMMON_DATA_DPATH, APP_GLOBAL_DATA_DPATH, APP_GLOBAL_RESOURCES_DPATH, APP_IS_BUNDLED, APP_ROOT_DPATH
from src.sks_retriever.sk_vars import APP_STEAM_CACHE_DPATH
APP_NAME = 'SKSAppManifestGenerator'
APP_VERSION = '2.0.3'
APP_RESOURCES_DPATH = APP_GLOBAL_RESOURCES_DPATH if APP_IS_BUNDLED else APP_GLOBAL_RESOURCES_DPATH / APP_NAME
APP_DATA_DPATH = APP_ROOT_DPATH / APP_NAME if APP_IS_BUNDLED else APP_GLOBAL_DATA_DPATH / APP_NAME
APP_LOGS_DPATH = APP_DATA_DPATH / 'logs'
APP_OUTPUT_DPATH = APP_DATA_DPATH
APP_CACHE_DPATH = APP_STEAM_CACHE_DPATH if APP_IS_BUNDLED else APP_GLOBAL_COMMON_DATA_DPATH / 'steam_cache'
APP_ICON_FPATH = h_get_project_icon(APP_RESOURCES_DPATH)
APP_LOG_FPATH = APP_LOGS_DPATH / f"{APP_NAME}.log"